// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMGz6AIRXgu7GVZiJWlkvO6tVZADf5tY',
    appId: '1:661929781606:web:3f306a659ae64ac7f780a7',
    messagingSenderId: '661929781606',
    projectId: 'funzy-d56d7',
    authDomain: 'funzy-d56d7.firebaseapp.com',
    storageBucket: 'funzy-d56d7.firebasestorage.app',
    measurementId: 'G-J4JX2WVWH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJx50VfAYcAa_C-9OxFaXNb_UYBYWv3BM',
    appId: '1:661929781606:android:56a13272d99e6865f780a7',
    messagingSenderId: '661929781606',
    projectId: 'funzy-d56d7',
    storageBucket: 'funzy-d56d7.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ2Fc0xTxvCZFdD47vc8ls0LNfzvVz5So',
    appId: '1:661929781606:ios:f5a7aa65f4440bfcf780a7',
    messagingSenderId: '661929781606',
    projectId: 'funzy-d56d7',
    storageBucket: 'funzy-d56d7.firebasestorage.app',
    androidClientId: '661929781606-c3lj4r1ufg1350tdd8vsdlemois1j1cb.apps.googleusercontent.com',
    iosBundleId: 'com.futa.clasha',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ2Fc0xTxvCZFdD47vc8ls0LNfzvVz5So',
    appId: '1:661929781606:ios:08d487fb009e66b8f780a7',
    messagingSenderId: '661929781606',
    projectId: 'funzy-d56d7',
    storageBucket: 'funzy-d56d7.firebasestorage.app',
    androidClientId: '661929781606-c3lj4r1ufg1350tdd8vsdlemois1j1cb.apps.googleusercontent.com',
    iosBundleId: 'com.tech.clash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWMGz6AIRXgu7GVZiJWlkvO6tVZADf5tY',
    appId: '1:661929781606:web:7f02493b361b12bef780a7',
    messagingSenderId: '661929781606',
    projectId: 'funzy-d56d7',
    authDomain: 'funzy-d56d7.firebaseapp.com',
    storageBucket: 'funzy-d56d7.firebasestorage.app',
    measurementId: 'G-F55G25QGZV',
  );
}
