// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb4rIhioT4vMPZjSjSXG-Y7iKY4CuAr9I',
    appId: '1:1095645826942:web:a8d0a51955731f17b1ad2f',
    messagingSenderId: '1095645826942',
    projectId: 'Funzy-66865',
    authDomain: 'Funzy-66865.firebaseapp.com',
    storageBucket: 'Funzy-66865.firebasestorage.app',
    measurementId: 'G-55YVBHY26F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAKUT0cq09FAF4BIoFOwz96XC4RtyvH14',
    appId: '1:1095645826942:android:95aec01bd16621dbb1ad2f',
    messagingSenderId: '1095645826942',
    projectId: 'Funzy-66865',
    storageBucket: 'Funzy-66865.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDquynDNGLuWXQzqSMpZIMdNs5Wi-H5q90',
    appId: '1:1095645826942:ios:58c29ecf5c2c3b4db1ad2f',
    messagingSenderId: '1095645826942',
    projectId: 'Funzy-66865',
    storageBucket: 'Funzy-66865.firebasestorage.app',
    iosBundleId: 'com.tech.Funzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDquynDNGLuWXQzqSMpZIMdNs5Wi-H5q90',
    appId: '1:1095645826942:ios:a6b44d8237fb663cb1ad2f',
    messagingSenderId: '1095645826942',
    projectId: 'Funzy-66865',
    storageBucket: 'Funzy-66865.firebasestorage.app',
    iosBundleId: 'com.tech.Funzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb4rIhioT4vMPZjSjSXG-Y7iKY4CuAr9I',
    appId: '1:1095645826942:web:f8712cc037704511b1ad2f',
    messagingSenderId: '1095645826942',
    projectId: 'Funzy-66865',
    authDomain: 'Funzy-66865.firebaseapp.com',
    storageBucket: 'Funzy-66865.firebasestorage.app',
    measurementId: 'G-V96GG4MWTB',
  );
}
