import 'package:flutter/foundation.dart';

class AdHelper {
  static const String productionNativeAdUnitId =
      'ca-app-pub-8671302794311438/1354354005';

  static const String productionCarouselAdUnitId1 =
      'ca-app-pub-8671302794311438/3524169425';
  static const String productionCarouselAdUnitId2 =
      'ca-app-pub-8671302794311438/4130674080';
  static const String productionCarouselAdUnitId3 =
      'ca-app-pub-8671302794311438/1504510743';

  // Google's official test ad unit IDs (different IDs per slot)
  static const String _testNativeAdUnitId1 =
      'ca-app-pub-3940256099942544/2247696110';
  static const String _testNativeAdUnitId2 =
      'ca-app-pub-3940256099942544/1044960115';
  static const String _testNativeAdUnitId3 =
      'ca-app-pub-3940256099942544/2247696110';

  // Rely solely on kDebugMode — Platform.environment doesn't
  // expose Android system properties so isEmulator was always false
  static String get postsFeedNativeAdUnitId {
    if (kDebugMode) return _testNativeAdUnitId1;
    return productionNativeAdUnitId;
  }

  static String get carouselAdUnitId1 {
    if (kDebugMode) return _testNativeAdUnitId1;
    return productionCarouselAdUnitId1;
  }

  static String get carouselAdUnitId2 {
    if (kDebugMode) return _testNativeAdUnitId2;
    return productionCarouselAdUnitId2;
  }

  static String get carouselAdUnitId3 {
    if (kDebugMode) return _testNativeAdUnitId3;
    return productionCarouselAdUnitId3;
  }

  static List<String> get carouselAdUnitIds {
    return [carouselAdUnitId1, carouselAdUnitId2, carouselAdUnitId3];
  }

  // ===========================================================================
  // WEB (AdSense) — separate namespace from AdMob above.
  // Client ID + In-feed slot IDs, used only inside kIsWeb branches via
  // dart:ui_web HtmlElementView, never with AdMob's NativeAd/AdWidget.
  // ===========================================================================

  static const String adSenseClientId = 'ca-pub-4829747375056254';

  // In-feed fluid ad units — all five share this layout-key, generated by
  // AdSense per-unit at creation time. If you create a new in-feed unit,
  // confirm its layout-key matches before adding it here.
  static const String adSenseInFeedLayoutKey = '-fb+5w+4e-db+86';

  static const List<String> adSenseInFeedSlotIds = [
    '5454601642', // funspot2
    '9051548379', // funspot3
    '3164796870', // funspot4
    '1372263706', // funspot5
    '7379268852', // funspot6
  ];
}
